### ISSUE TITLE
能不能设置成自己控制启停和重置呢？

### ISSUE THREAD

**Issue by zhangwei900808** [satrong/vue-text-marquee#1]
现在的效果是自动跑，我想自己控制它的跑和停，能不能提供这样的效果

**Comment by satrong** [comment]
感谢你提供的建议，这个功能可以加上。加上了会通知你。

**Comment by satrong** [comment]
@zhangwei900808 开启与暂停已加上，参考文档。重置暂时想不到应用场景。
